EMPLOYD/urls.py
from django.urls import path
from . import views

app_name = 'employd'
urlpatterns = [
    # ex: /employd/ -- List of all Work Records
    path('', views.index, name='index'),
    # ex: /employd/data -- List of all Work Records (table data call)
    path('data', views.index_json_table_data, name='loadtable'),
    # ex: /employd/wr/12 -- Update a WorkRecord
    path('wr/<int:pk>/', views.WorkRecordUpdateView.as_view(),
         name='workrecordupdate'),
    # ex: /employd/wr/create -- Create a new WorkRecord
    path('wr/create', views.WorkRecordCreate.as_view(), name='workrecordcreate'),
<<<<<<< HEAD:EMPLOYD/urls.py
    # ex: /employd/wr/delete -- Delete an existing WorkRecord
    path('wr/<int:pk>/delete', views.WorkRecordDelete.as_view(), name='workrecorddelete'),
=======
    # ex: /pewad/wr/delete -- Delete an existing WorkRecord
    path('wr/<int:pk>/delete', views.WorkRecordDelete.as_view(),
         name='workrecorddelete'),
>>>>>>> 61757ad75744f2621691834348b16edca1a4ca61:pewad/urls.py

    # ex: /lead/emailall -- Send emails to all Leads with team tasking breakdowns
    path('lead/emailall', views.email_all_leads, name='leademailall'),

    # ex: /employd/employee/list -- List of all employees
    path('employee/list', views.employee_list, name='employeelist'),
    # ex: /employd/employee/list/data -- List of all employees (table data call)
    path('employee/list/data', views.employee_json_table_data,
         name='employeelistdata'),
    # ex: /employd/employee/4 -- Detail/Update view of a single employee
    path('employee/<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee'),
    # ex: /employd/employee/4/records -- Detail/Update view of a single employee (table data call)
    path('employee/<int:emp_id>/records',
         views.employee_json_records, name='employeerecords'),
    # ex: /employd/employee/4/email -- Sends an email to the employee with a WorkRecord table
    path('employee/<int:pk>/email',
         views.email_single_employee, name='employeeemail'),
    # ex: /employd/employee/emailall -- Sends emails to all employee with a WorkRecord table
    path('employee/emailall',
         views.email_all_employees, name='employeeemailall'),
    # ex: /employd/employee/create -- Create a new Employee
    path('employee/create', views.EmployeeCreate.as_view(), name='employeecreate'),

    # ex: /employd/contract/list -- List of all contracts
    path('contract/list', views.contract_list, name='contractlist'),
    # ex: /employd/contract/list/data -- List of all contracts (table data call)
    path('contract/list/data', views.contract_json_table_data,
         name="contractlistdata"),
    # ex: /employd/contract/12 -- Detail/Update view of a single contract
    path('contract/<int:pk>/', views.ContractUpdateView.as_view(), name='contract'),
    # ex: /employd/contract/12/records -- Detail/Update view of a single contract (table data call)
    path('contract/<int:pk>/records',
         views.contact_json_records, name='contractrecords'),
    # ex: pewad/contract/create -- Create a new Contract Listing
    path('contract/create', views.ContractCreate.as_view(), name='contractcreate'),

    # ex: /employd/project/list -- List of all projects
    path('project/list', views.project_list, name='projectlist'),
    # ex: /employd/project/list/data -- List of all projects (table data call)
    path('project/list/data', views.project_json_table_data,
         name="projectlistdata"),
    # ex: /employd/project/12 -- Detail/Update view of a single project
    path('project/<int:pk>/', views.ProjectUpdateView.as_view(), name='project'),
    # ex: /employd/project/12/records -- Detail/Update view of a single project (table data call)
    path('project/<int:pk>/records',
         views.contact_json_records, name='projectrecords'),
    # ex: /pewad/project/create -- Create a new Project
    path('project/create', views.ProjectCreate.as_view(), name='projectcreate'),
]

madrox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('employd/', include('employd.urls')),
    path('admin/', admin.site.urls),
]

pewad/urls.py
from django.urls import path
from . import views

app_name = 'pewad'
urlpatterns = [
    # ex: /pewad/ -- List of all Work Records
    path('', views.index, name='index'),
    # ex: /pewad/data -- List of all Work Records (table data call)
    path('data', views.index_json_table_data, name='loadtable'),
    # ex: /pewad/wr/12 -- Update a WorkRecord
    path('wr/<int:pk>/', views.WorkRecordUpdateView.as_view(),
         name='workrecordupdate'),
    # ex: /pewad/wr/create -- Create a new WorkRecord
    path('wr/create', views.WorkRecordCreate.as_view(), name='workrecordcreate'),
    # ex: /pewad/wr/delete -- Delete an existing WorkRecord
    path('wr/<int:pk>/delete', views.WorkRecordDelete.as_view(),
         name='workrecorddelete'),

    # ex: /lead/emailall -- Send emails to all Leads with team tasking breakdowns
    path('lead/emailall', views.email_all_leads, name='leademailall'),

    # ex: /pewad/employee/list -- List of all employees
    path('employee/list', views.employee_list, name='employeelist'),
    # ex: /pewad/employee/list/data -- List of all employees (table data call)
    path('employee/list/data', views.employee_json_table_data,
         name='employeelistdata'),
    # ex: /pewad/employee/4 -- Detail/Update view of a single employee
    path('employee/<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee'),
    # ex: /pewad/employee/4/records -- Detail/Update view of a single employee (table data call)
    path('employee/<int:emp_id>/records',
         views.employee_json_records, name='employeerecords'),
    # ex: /pewad/employee/4/email -- Sends an email to the employee with a WorkRecord table
    path('employee/<int:pk>/email',
         views.email_single_employee, name='employeeemail'),
    # ex: /pewad/employee/emailall -- Sends emails to all employee with a WorkRecord table
    path('employee/emailall',
         views.email_all_employees, name='employeeemailall'),
    # ex: /pewad/employee/create -- Create a new Employee
    path('employee/create', views.EmployeeCreate.as_view(), name='employeecreate'),

    # ex: /pewad/contract/list -- List of all contracts
    path('contract/list', views.contract_list, name='contractlist'),
    # ex: /pewad/contract/list/data -- List of all contracts (table data call)
    path('contract/list/data', views.contract_json_table_data,
         name="contractlistdata"),
    # ex: /pewad/contract/12 -- Detail/Update view of a single contract
    path('contract/<int:pk>/', views.ContractUpdateView.as_view(), name='contract'),
    # ex: /pewad/contract/12/records -- Detail/Update view of a single contract (table data call)
    path('contract/<int:pk>/records',
         views.contact_json_records, name='contractrecords'),
    # ex: pewad/contract/create -- Create a new Contract Listing
    path('contract/create', views.ContractCreate.as_view(), name='contractcreate'),

    # ex: /pewad/project/list -- List of all projects
    path('project/list', views.project_list, name='projectlist'),
    # ex: /pewad/project/list/data -- List of all projects (table data call)
    path('project/list/data', views.project_json_table_data,
         name="projectlistdata"),
    # ex: /pewad/project/12 -- Detail/Update view of a single project
    path('project/<int:pk>/', views.ProjectUpdateView.as_view(), name='project'),
    # ex: /pewad/project/12/records -- Detail/Update view of a single project (table data call)
    path('project/<int:pk>/records',
         views.contact_json_records, name='projectrecords'),
    # ex: /pewad/project/create -- Create a new Project
    path('project/create', views.ProjectCreate.as_view(), name='projectcreate'),
]

EMPLOYD/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from django.core.mail import send_mail
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMultiAlternatives, get_connection
from django.utils.html import strip_tags
from django.utils.datastructures import MultiValueDict
import pprint

from .models import Contract, Employee, Project, WorkRecord


# ------------------------------------------------------------
# -------------------- Main (index) Views --------------------
# ------------------------------------------------------------


def index(request):
    """ Display the default employd landing page"""
    context = {'passedValue': "MADROX", }
    return render(request, 'employd/index.html', context)


def index_json_table_data(request):
    """ GET JSON data for table view; WorkRecords """
    dbRecs = get_list_or_404(WorkRecord)
    data = workrecord_models_to_json(dbRecs)

    return JsonResponse(data, safe=False)


class WorkRecordUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display WorkRecord update form, for use inside a modal """
    model = WorkRecord
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class WorkRecordCreate(SuccessMessageMixin, generic.CreateView):
    """ Create a new WorkRecord, via modal """
    model = WorkRecord
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Work Record \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class WorkRecordDelete(SuccessMessageMixin, generic.DeleteView):
    """ Deletes a WorkRecord, with confirmation """
    model = WorkRecord

    def get_success_message(self, cleaned_data):
        return "Work Record \"%s\" was successfully deleted." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

# ------------------------------------------------------------
# -------------------- Employee Views ------------------------
# ------------------------------------------------------------


class EmployeeCreate(SuccessMessageMixin, generic.CreateView):
    """ Create a new Employee """
    model = Employee
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Employee \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_invalid(self, form):
        messages.error(self.request, 'Error: failed create')


def employee_list(request):
    """ Display list view showing all Employees """

    return render(request, 'employd/employee_list.html', {'list_title': 'Employee'})


def employee_json_table_data(request):
    """ GET JSON data for all Employees list view """
    dbrecs = get_list_or_404(Employee)
    data = serialize('json', dbrecs, cls=LazyEncoder)

    return HttpResponse(data, content_type="json")


class EmployeeUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display view for updating an Employee  """
    model = Employee
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."


def employee_json_records(request, emp_id):
    """ Get the WorkRecords data in JSON for an Employee """
    records = WorkRecord.objects.filter(emp=emp_id)
    data = workrecord_models_to_json(records)

    return JsonResponse(data, safe=False)


# ------------------------------------------------------------
# -------------------- Contract Views ------------------------
# ------------------------------------------------------------
class ContractCreate(SuccessMessageMixin, generic.CreateView):
    "Create a new contract via a create contract form"
    model = Contract
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Contract \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_invalid(self, form):
        messages.error(self.request, 'Error: failed create')


def contract_list(request):
    """ Display list view showing all Contracts """

    return render(request, 'employd/contract_list.html', {'list_title': 'Contracts'})


def contract_json_table_data(request):
    """ GET JSON data for all Contracts list view """
    conts = get_list_or_404(Contract)
    data = serialize('json', conts)

    return HttpResponse(data, content_type="json")


class ContractUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display view for updating a Contract """
    model = Contract
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."


def contact_json_records(request, pk):
    """ Get the WorkRecords data in JSON for a Contact """
    records = WorkRecord.objects.filter(cont=pk)
    data = workrecord_models_to_json(records)

    return JsonResponse(data, safe=False)

# ------------------------------------------------------------
# -------------------- Project Views -------------------------
# ------------------------------------------------------------


class ProjectCreate(SuccessMessageMixin, generic.CreateView):
    """ Create a new Project """
    model = Project
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Project \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_invalid(self, form):
        messages.error(self.request, 'Error: failed create')


def project_list(request):
    """ Display list view showing all Projects """

    return render(request, 'employd/project_list.html', {'list_title': 'Project'})


def project_json_table_data(request):
    """ GET JSON data for all Projects list view """
    projs = get_list_or_404(Project)
    data = serialize('json', projs)

    return HttpResponse(data, content_type="json")


class ProjectUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display view for updating a Project """
    model = Project
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."


def project_json_records(request, pk):
    """ Get the WorkRecords data in JSON for a Project """
    records = WorkRecord.objects.filter(proj=pk)
    data = workrecord_models_to_json(records)

    return JsonResponse(data, safe=False)

# ------------------------------------------------------------
# -------------------- Email Stuffs --------------------------
# ------------------------------------------------------------


def generate_email(recipient, subject, body):
    """ Generic email creation """
    plaintext_msg = strip_tags(body)
    email = EmailMultiAlternatives(
        subject, plaintext_msg, 'admin@gblsys.com', [recipient])
    email.attach_alternative(body, "text/html")

    return email


def create_email_message(work_records):
    """ Creates an email body string from a template """
    table_rows = ""
    for rec in work_records:
        rd = {'cont': rec.cont, 'proj': rec.proj.abbr,
              'lead': rec.lead, 'hours': rec.hours, 'task': rec.task}
        table_rows += render_to_string("email/tablerow.html", rd)
    msgparams = {'name': work_records[0].emp, 'rows': table_rows}

    return render_to_string("email/email.html", msgparams)


def email_single_employee(request, pk):
    """ Email an Employee's WorkRecords to the employee """
    recip = get_object_or_404(Employee, pk=pk)
    records = WorkRecord.objects.filter(emp=pk).order_by('-hours')

    sub_msg = '%s Work Assignment' % recip.lname
    body = create_email_message(records)
    email = generate_email(recip.email, sub_msg, body)
    try:
        email.send()
        return HttpResponse(status=200)
    except ConnectionRefusedError:
        messages.error(request, 'Error: Failed to connect to mail server.')
    except Exception:
        messages.error(request, 'Error: Email failed, contact administrator.')

    return HttpResponse(status=400)


def email_all_employees(request):
    """ Email all WorkRecords in the system for each employee """
    all_emails = []
    for emp in Employee.objects.all():
        recs = emp.workrecord_set.order_by('-hours')
        if recs:
            email = generate_html_email(emp, recs)
            all_emails.append(email)
    if all_emails:
        connection = get_connection()
        connection.send_messages(all_emails)

    return HttpResponse(status=200)


def create_lead_message(work_records):
    """ Creates an email body string from a template; for agregated lead email """

    recs_by_emp = MultiValueDict()
    for r in work_records:
        recs_by_emp.appendlist(r.emp, r)

    for rec in recs_by_emp:
        rd = {'emp': rec.emp, 'cont': rec.cont, 'proj': rec.proj.abbr,
              'hours': rec.hours, 'task': rec.task}
        table_rows += render_to_string("email/leadrow.html", rd)
    msgparams = {'name': work_records[0].lead, 'rows': table_rows}

    return render_to_string("email/lead.html", msgparams)


def email_all_leads(request):
    """ Email all leads a compiled list of all WorkRecords for all their employees """
    all_supervisors_emails = []

    sorted_by_lead_email = MultiValueDict()

EMPLOYD/templates/EMPLOYD/basecss.html
{% load staticfiles %}

{% if debug %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/css/tabulator.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.css" rel="stylesheet">
{% else %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/css/tabulator.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css" rel="stylesheet">
{% endif %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'employd/style.css' %}">

EMPLOYD/templates/EMPLOYD/basehtml.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
    {% include 'employd/basecss.html' %} 
    {% include 'employd/basejs.html' %} 
    {% block head %}{% endblock %}
    <title>
        {% if debug %}DEBUG {% endif %}{% block title %}{% endblock %}
    </title>
</head>
<body>
    <nav class="purple">
        <div class="nav-wrapper">
            <a class="brand-logo" href="{% url 'employd:index' %}">
                <img src="{% static 'employd/images/mm-round.png' %}" height="30" width="30" alt="logo" style="position:relative; top:5px; margin-left:10px;"> employd
            </a>
            <ul id="nav" class="right">
                <li><a class="nav-item nav-link" href="{% url 'employd:contractlist' %}">Contracts</a></li>
                <li><a class="nav-item nav-link" href="{% url 'employd:projectlist' %}">Projects</a></li>
                <li><a class="nav-item nav-link" href="{% url 'employd:employeelist' %}">Employees</a></li>
            </ul>
        </div>
    </nav>
    <div id="modal-container"></div>
    <div id="content" class="container" style="width: 90%">
        <div class="row" id="alert_box">
            {% if messages %}
                <div id="alert_msgs" class="col s12 m12">
                    {% for message in messages %}
                    <div class="card {{ message.tags }}">
                        <div class="row">
                            <div class="col s12 m10">
                                <div class="card-content">
                                    <strong>{{ message }}</strong>
                                </div>
                            </div>
                            <div class="col s12 m2">
                                <i class="material-icons icon_style" id="alert_close" aria-hidden="true">close</i>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        {% block body %} {% endblock %} 
        {% block footer %} {% endblock %}
    </div>
    <script type="text/javascript">
        $('#alert_close').on('click', function () {
            /* Closes alert messages */
            $("#alert_box").fadeOut("slow", function () {});
        });

        function loadAndOpenModal(url) {
            /* Make a GET request for a form and launches it in a modal */
            $.get(url, function (result) {
                $('#modal-container').html(result);
                $('.modal').modal();
                $('#modal').modal('open');
            });
        }
    </script>
</body>
</html>

EMPLOYD/templates/EMPLOYD/contract_list.html
{% extends 'employd/list.html' %}

{% block extra-buttons %}
<a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Contract">
    <i class="material-icons left">note_add</i>Create New Contract</a>
{% endblock extra-buttons %}
{% block table-script %}
<<<<<<< HEAD:EMPLOYD/templates/EMPLOYD/contract_list.html
    <script type="text/javascript">
        $(document).ready(function () {
            /* Build the table here; settings adjustments */
            $("#list-table").tabulator({
                ajaxURL: "{% url 'employd:contractlistdata' %}", // Load table data
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                layout: "fitDataFill", //fit columns to width of table (optional)
                columns: [ //Define Table Columns
                    { title: "ID", field: "pk", sorter: "number" },
                    { title: "Name", field: "fields.name", sorter: "string" },
                    { title: "Number", field: "fields.number", sorter: "number" },
                ],
                rowClick: function (e, id) {
                    location.href = id.row.data.pk;
                },
            });
=======
<script type="text/javascript">
    $(document).ready(function () {
        /* Build the table here; settings adjustments */
        $("#list-table").tabulator({
            ajaxURL: "{% url 'pewad:contractlistdata' %}", // Load table data
            clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
            layout: "fitDataFill", //fit columns to width of table (optional)
            initialSort: [{column: "fields.name", dir: "asc"},],
            columns: [ //Define Table Columns
                { title: "ID", field: "pk", sorter: "number" },
                { title: "Name", field: "fields.name", sorter: "string" },
                { title: "Number", field: "fields.number", sorter: "number" },
            ],
            rowClick: function (e, id) {
                location.href = id.row.data.pk;
            },
>>>>>>> 61757ad75744f2621691834348b16edca1a4ca61:pewad/templates/pewad/contract_list.html
        });
    });

    $("#createbutton").click(function () {
        var url = "{% url 'pewad:contractcreate' %}"
        loadAndOpenModal(url);
    });
</script>
{% endblock table-script %}

EMPLOYD/templates/EMPLOYD/employee_create_form.html
{% load materializecss %}
<div class="modal bottom-sheet" id="modal">
    <div class="modal-content">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat btn-small right">
            <i class="material-icons">close</i>
        </a>
        <h5>Create New Employee</h5>
        <div class="divider"></div>
        <div class="divider"></div>
<<<<<<< HEAD:EMPLOYD/templates/EMPLOYD/employee_create_form.html
        <form method="POST" action="{% url 'employd:employeecreate' %}">
            {% csrf_token %} 
            {{ form.as_p }}
            <input type="submit" value="Create" class="waves-effect waves-green btn-flat btn-small" />
=======
        <form method="POST" action="{% url 'pewad:employeecreate' %}">
            <div class="row">
                {% csrf_token %}
                {{ form | materializecss }}
                <input type="submit" value="Create" class="waves-effect waves-green btn-flat btn-small" />
            </div>
>>>>>>> 61757ad75744f2621691834348b16edca1a4ca61:pewad/templates/pewad/employee_create_form.html
        </form>
    </div>
</div>

EMPLOYD/templates/EMPLOYD/employee_list.html
{% extends 'employd/list.html' %}

{% block extra-buttons %}
    <a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Employee">
        <i class="material-icons left">person_add</i>Create New Employee</a>
    <a id="emailallbutton" class="waves-effect waves-light btn-small" title="Email All Employees">
        <i class="material-icons left">email</i>Email All Employees</a>
    <a id="emailleadsbutton" class="waves-effect waves-light btn-small" title="Email All Leads">
        <i class="material-icons left">email</i>Email Lead Reports</a>
{% endblock extra-buttons %}
{% block table-script %}
    <script type="text/javascript">
        $(document).ready(function () {
            /* Build the table here; settings adjustments */
            $("#list-table").tabulator({
                ajaxURL: "{% url 'employd:employeelistdata' %}", // Load table data
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                layout: "fitDataFill", //fit columns to width of table (optional)
                initialSort: [{ column: "fields.lname", dir: "asc" },],
                columns: [ //Define Table Columns
                    { title: "ID", field: "pk", sorter: "number" },
                    { title: "Last", field: "fields.lname", sorter: "string" },
                    { title: "First", field: "fields.fname", sorter: "string" },
                    { title: "Email", field: "fields.email", sorter: "string" }
                ],
                rowClick: function (e, id) {
                    location.href = id.row.data.pk;
                },
            });
        });

        $("#createbutton").click(function () {
            var url = "{% url 'employd:employeecreate' %}"
            loadAndOpenModal(url);
        });
        $("#emailallbutton").click(function () {
            var url = "{% url 'employd:employeeemailall' %}"
            $.get(url, function (result) { });
            M.toast({ html: 'Emailing all employees.' });
        });
        $("#emailleadsbutton").click(function() {
            var url = "{% url 'employd:leademailall' %}";
            M.toast({ html: 'Emailing all Leads...' });
            $.get(url, function (result) { });
        });
    </script>
{% endblock table-script %}

EMPLOYD/templates/EMPLOYD/employee_update.html
{% extends 'employd/update.html' %}

{% block title %}Employee Record: {{ employee.fname }} {{ employee.lname }}{% endblock title%}
{% block item-desc %}{{ employee.fname }} {{ employee.lname }}{% endblock item-desc %}
{% block helper-buttons %}
    <a id="emailbutton" class="waves-effect waves-light btn-small" title="Email Records to {{ employee.fname }}">
        <i class="material-icons left">email</i>Email</a>
{% endblock helper-buttons %}
{% block table-script %}
    <script type="text/javascript">
        $(document).ready(function () {
            /* Build the main table here; settings adjustments */
            $("#record-table").tabulator({
                ajaxURL: "{% url 'employd:employeerecords' employee.id %}", // Load table data
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                height: false, // set height of table to enable virtual DOM
                layout: "fitDataFill", //fit columns to width of table (optional)
                layoutColumnsOnNewData: true, // fixes row heights (see: textarea) on data load
                columns: [ //Define Table Columns
                    { //Contract Column Group
                        title: "Contract",
                        columns: [
                            { title: "Number", field: "conNum", sorter: "string" },
                            { title: "Name", field: "conName", sorter: "string" },
                        ],
                    },
                    { title: "Project", field: "proj", sorter: "string" },
                    { // Lead Column Group
                        title: "Lead",
                        columns: [
                            { title: "Last", field: "leadLast", sorter: "string" },
                            { title: "First", field: "leadFirst", sorter: "string" },
                        ],
                    },
                    { title: "WBS Hours", field: "hours", sorter: "number", bottomCalc: "sum" },
                    { title: "Work Assignment", field: "assig", sortable: false, formatter: "textarea" },
                ],
                rowClick: function (e, t) {
                    // On row click, open a WorkRecord edit modal
                    var url = "{% url 'employd:workrecordupdate' 0 %}";
                    url = url.replace("0", t.row.data.pk);
                    loadAndOpenModal(url);
                },
            });
        });

        $('#emailbutton').click(function(){
            $.ajax({
                url: "{% url 'employd:employeeemail' employee.id %}",
                type: 'GET',
                success: function(data){ 
                    M.toast({html: 'Email successfully sent!', displayLength: 10000});
                },
                error: function(data) {
                    location.reload();
                }
            });
        });
    </script>
{% endblock table-script %}

EMPLOYD/templates/EMPLOYD/project_list.html
{% extends 'employd/list.html' %}

{% block extra-buttons %}
    <a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Project">
        <i class="material-icons left">playlist_add</i>Create New Project</a>
{% endblock extra-buttons %}
{% block table-script %}
    <script type="text/javascript">
        $(document).ready(function () {
            /* Build the table here; settings adjustments */
            $("#list-table").tabulator({
                ajaxURL: "{% url 'employd:projectlistdata' %}", // Load table data
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                layout: "fitDataFill", //fit columns to width of table (optional)
                initialSort: [{ column: "fields.abbr", dir: "asc" },],
                columns: [ //Define Table Columns
                    { title: "ID", field: "pk", sorter: "number" },
                    { title: "Abbreviation", field: "fields.abbr", sorter: "string" },
                    { title: "Name", field: "fields.name", sorter: "string" },
                ],
                rowClick: function (e, id) {
                    location.href = id.row.data.pk;
                },
            });
        });

        $("#createbutton").click(function () {
            var url = "{% url 'pewad:projectcreate' %}"
            loadAndOpenModal(url);
        });
    </script>
{% endblock table-script %}