madrox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('employd/', include('employd.urls')),
    path('admin/', admin.site.urls),
]

pewad/urls.py
from django.urls import path
from . import views

app_name = 'pewad'
urlpatterns = [
    # ex: /pewad/ -- List of all Work Records
    path('', views.index, name='index'),
    # ex: /pewad/data -- List of all Work Records (table data call)
    path('data', views.index_json_table_data, name='loadtable'),
    # ex: /pewad/wr/12 -- Update a WorkRecord
    path('wr/<int:pk>/', views.WorkRecordUpdateView.as_view(),
         name='workrecordupdate'),
    # ex: /pewad/wr/create -- Create a new WorkRecord
    path('wr/create', views.WorkRecordCreate.as_view(), name='workrecordcreate'),
    # ex: /pewad/wr/delete -- Delete an existing WorkRecord
    path('wr/<int:pk>/delete', views.WorkRecordDelete.as_view(),
         name='workrecorddelete'),

    # ex: /lead/emailall -- Send emails to all Leads with team tasking breakdowns
    path('lead/emailall', views.email_all_leads, name='leademailall'),

    # ex: /pewad/employee/list -- List of all employees
    path('employee/list', views.employee_list, name='employeelist'),
    # ex: /pewad/employee/list/data -- List of all employees (table data call)
    path('employee/list/data', views.employee_json_table_data,
         name='employeelistdata'),
    # ex: /pewad/employee/4 -- Detail/Update view of a single employee
    path('employee/<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee'),
    # ex: /pewad/employee/4/records -- Detail/Update view of a single employee (table data call)
    path('employee/<int:emp_id>/records',
         views.employee_json_records, name='employeerecords'),
    # ex: /pewad/employee/4/email -- Sends an email to the employee with a WorkRecord table
    path('employee/<int:pk>/email',
         views.email_single_employee, name='employeeemail'),
    # ex: /pewad/employee/emailall -- Sends emails to all employee with a WorkRecord table
    path('employee/emailall',
         views.email_all_employees, name='employeeemailall'),
    # ex: /pewad/employee/create -- Create a new Employee
    path('employee/create', views.EmployeeCreate.as_view(), name='employeecreate'),

    # ex: /pewad/contract/list -- List of all contracts
    path('contract/list', views.contract_list, name='contractlist'),
    # ex: /pewad/contract/list/data -- List of all contracts (table data call)
    path('contract/list/data', views.contract_json_table_data,
         name="contractlistdata"),
    # ex: /pewad/contract/12 -- Detail/Update view of a single contract
    path('contract/<int:pk>/', views.ContractUpdateView.as_view(), name='contract'),
    # ex: /pewad/contract/12/records -- Detail/Update view of a single contract (table data call)
    path('contract/<int:pk>/records',
         views.contact_json_records, name='contractrecords'),
    # ex: pewad/contract/create -- Create a new Contract Listing
    path('contract/create', views.ContractCreate.as_view(), name='contractcreate'),

    # ex: /pewad/project/list -- List of all projects
    path('project/list', views.project_list, name='projectlist'),
    # ex: /pewad/project/list/data -- List of all projects (table data call)
    path('project/list/data', views.project_json_table_data,
         name="projectlistdata"),
    # ex: /pewad/project/12 -- Detail/Update view of a single project
    path('project/<int:pk>/', views.ProjectUpdateView.as_view(), name='project'),
    # ex: /pewad/project/12/records -- Detail/Update view of a single project (table data call)
    path('project/<int:pk>/records',
         views.contact_json_records, name='projectrecords'),
    # ex: /pewad/project/create -- Create a new Project
    path('project/create', views.ProjectCreate.as_view(), name='projectcreate'),
]

pewad/models.py
from django.db import models
from django.urls import reverse


class BaseModel(models.Model):
    # All other models should inherits from this to include extras
    def classname(self):
        return self.__class__.__name__

    def meta(self):
        return self._meta

    class Meta:
        abstract = True


class Employee(BaseModel):
    # Employee database model
    fname = models.CharField("First Name", max_length=200)
    lname = models.CharField("Last Name", max_length=200)
    email = models.EmailField("Email", null=False)

    def __str__(self):
        return "{self.fname} {self.lname}".format(self=self)

    def get_absolute_url(self):
        return reverse('pewad:employee', kwargs={'pk': self.pk})


class Project(BaseModel):
    # Project database model
    name = models.CharField("Project Name", max_length=500)
    abbr = models.CharField("Abbr.", max_length=100)
    desc = models.TextField("Description")

    def __str__(self):
        return "{self.name} ({self.abbr})".format(self=self)

    def get_absolute_url(self):
        return reverse('pewad:project', kwargs={'pk': self.pk})


class Contract(BaseModel):
    # Contract database model
    name = models.CharField("Contract Name", max_length=200)
    number = models.IntegerField("Contract Number")

    def __str__(self):
        return "{self.number} {self.name}".format(self=self)

    def get_absolute_url(self):
        return reverse('pewad:contract', kwargs={'pk': self.pk})


class WorkRecord(BaseModel):
    # Work Record (Tasking) database model
    cont = models.ForeignKey(
        Contract,
        verbose_name="Contract",
        on_delete=models.CASCADE,
    )
    proj = models.ForeignKey(
        Project,
        verbose_name="Project",
        on_delete=models.CASCADE,
    )
    emp = models.ForeignKey(
        Employee,
        verbose_name="Employee",
        on_delete=models.CASCADE,
    )
    lead = models.ForeignKey(
        Employee,
        verbose_name="Lead",
        on_delete=models.CASCADE,
        related_name="Lead",
        null=True,
    )
    hours = models.CharField("Hours", max_length=4)
    task = models.TextField("Assignment")

    def __str__(self):
        return "{self.emp}: {self.proj.abbr} - {self.task}".format(self=self)

pewad/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from django.core.mail import send_mail
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMultiAlternatives, get_connection
from django.utils.html import strip_tags
from django.utils.datastructures import MultiValueDict
import pprint

from .models import Contract, Employee, Project, WorkRecord


# ------------------------------------------------------------
# -------------------- Main (index) Views --------------------
# ------------------------------------------------------------


def index(request):
    """ Display the default PEWAD landing page"""
    context = {'passedValue': "MADROX", }
    return render(request, 'pewad/index.html', context)


def index_json_table_data(request):
    """ GET JSON data for table view; WorkRecords """
    dbRecs = get_list_or_404(WorkRecord)
    data = workrecord_models_to_json(dbRecs)

    return JsonResponse(data, safe=False)


class WorkRecordUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display WorkRecord update form, for use inside a modal """
    model = WorkRecord
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class WorkRecordCreate(SuccessMessageMixin, generic.CreateView):
    """ Create a new WorkRecord, via modal """
    model = WorkRecord
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Work Record \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class WorkRecordDelete(SuccessMessageMixin, generic.DeleteView):
    """ Deletes a WorkRecord, with confirmation """
    model = WorkRecord

    def get_success_message(self, cleaned_data):
        return "Work Record \"%s\" was successfully deleted." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

# ------------------------------------------------------------
# -------------------- Employee Views ------------------------
# ------------------------------------------------------------


class EmployeeCreate(SuccessMessageMixin, generic.CreateView):
    """ Create a new Employee """
    model = Employee
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Employee \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_invalid(self, form):
        messages.error(self.request, 'Error: failed create')


def employee_list(request):
    """ Display list view showing all Employees """

    return render(request, 'pewad/employee_list.html', {'list_title': 'Employee'})


def employee_json_table_data(request):
    """ GET JSON data for all Employees list view """
    dbrecs = get_list_or_404(Employee)
    data = serialize('json', dbrecs, cls=LazyEncoder)

    return HttpResponse(data, content_type="json")


class EmployeeUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display view for updating an Employee  """
    model = Employee
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."


def employee_json_records(request, emp_id):
    """ Get the WorkRecords data in JSON for an Employee """
    records = WorkRecord.objects.filter(emp=emp_id)
    data = workrecord_models_to_json(records)

    return JsonResponse(data, safe=False)


# ------------------------------------------------------------
# -------------------- Contract Views ------------------------
# ------------------------------------------------------------
class ContractCreate(SuccessMessageMixin, generic.CreateView):
    "Create a new contract via a create contract form"
    model = Contract
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Contract \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_invalid(self, form):
        messages.error(self.request, 'Error: failed create')


def contract_list(request):
    """ Display list view showing all Contracts """

    return render(request, 'pewad/contract_list.html', {'list_title': 'Contracts'})


def contract_json_table_data(request):
    """ GET JSON data for all Contracts list view """
    conts = get_list_or_404(Contract)
    data = serialize('json', conts)

    return HttpResponse(data, content_type="json")


class ContractUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display view for updating a Contract """
    model = Contract
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."


def contact_json_records(request, pk):
    """ Get the WorkRecords data in JSON for a Contact """
    records = WorkRecord.objects.filter(cont=pk)
    data = workrecord_models_to_json(records)

    return JsonResponse(data, safe=False)

# ------------------------------------------------------------
# -------------------- Project Views -------------------------
# ------------------------------------------------------------


class ProjectCreate(SuccessMessageMixin, generic.CreateView):
    """ Create a new Project """
    model = Project
    fields = '__all__'
    template_name_suffix = '_create_form'

    def get_success_message(self, cleaned_data):
        return "Project \"%s\" was added successfully." % self.object

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_invalid(self, form):
        messages.error(self.request, 'Error: failed create')


def project_list(request):
    """ Display list view showing all Projects """

    return render(request, 'pewad/project_list.html', {'list_title': 'Project'})


def project_json_table_data(request):
    """ GET JSON data for all Projects list view """
    projs = get_list_or_404(Project)
    data = serialize('json', projs)

    return HttpResponse(data, content_type="json")


class ProjectUpdateView(SuccessMessageMixin, generic.UpdateView):
    """ Display view for updating a Project """
    model = Project
    fields = '__all__'
    template_name_suffix = '_update'
    success_message = "Update successful."


def project_json_records(request, pk):
    """ Get the WorkRecords data in JSON for a Project """
    records = WorkRecord.objects.filter(proj=pk)
    data = workrecord_models_to_json(records)

    return JsonResponse(data, safe=False)

# ------------------------------------------------------------
# -------------------- Email Stuffs --------------------------
# ------------------------------------------------------------


def generate_email(recipient, subject, body):
    """ Generic email creation """
    plaintext_msg = strip_tags(body)
    email = EmailMultiAlternatives(
        subject, plaintext_msg, 'admin@gblsys.com', [recipient])
    email.attach_alternative(body, "text/html")

    return email


def create_email_message(work_records):
    """ Creates an email body string from a template """
    table_rows = ""
    for rec in work_records:
        rd = {'cont': rec.cont, 'proj': rec.proj.abbr,
              'lead': rec.lead, 'hours': rec.hours, 'task': rec.task}
        table_rows += render_to_string("email/tablerow.html", rd)
    msgparams = {'name': work_records[0].emp, 'rows': table_rows}

    return render_to_string("email/email.html", msgparams)


def email_single_employee(request, pk):
    """ Email an Employee's WorkRecords to the employee """
    recip = get_object_or_404(Employee, pk=pk)
    records = WorkRecord.objects.filter(emp=pk).order_by('-hours')

    sub_msg = '%s Work Assignment' % recip.lname
    body = create_email_message(records)
    email = generate_email(recip.email, sub_msg, body)
    try:
        email.send()
        return HttpResponse(status=200)
    except ConnectionRefusedError:
        messages.error(request, 'Error: Failed to connect to mail server.')
    except Exception:
        messages.error(request, 'Error: Email failed, contact administrator.')

    return HttpResponse(status=400)


def email_all_employees(request):
    """ Email all WorkRecords in the system for each employee """
    all_emails = []
    for emp in Employee.objects.all():
        recs = emp.workrecord_set.order_by('-hours')
        if recs:
            email = generate_html_email(emp, recs)
            all_emails.append(email)
    if all_emails:
        connection = get_connection()
        connection.send_messages(all_emails)

    return HttpResponse(status=200)


def create_lead_message(work_records):
    """ Creates an email body string from a template; for agregated lead email """

    recs_by_emp = MultiValueDict()
    for r in work_records:
        recs_by_emp.appendlist(r.emp, r)

    for rec in recs_by_emp:
        rd = {'emp': rec.emp, 'cont': rec.cont, 'proj': rec.proj.abbr,
              'hours': rec.hours, 'task': rec.task}
        table_rows += render_to_string("email/leadrow.html", rd)
    msgparams = {'name': work_records[0].lead, 'rows': table_rows}

    return render_to_string("email/lead.html", msgparams)


def email_all_leads(request):
    """ Email all leads a compiled list of all WorkRecords for all their employees """
    all_supervisors_emails = []

    sorted_by_lead_email = MultiValueDict()

pewad/templates/pewad/basehtml.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
    {% include 'pewad/basecss.html' %} 
    {% include 'pewad/basejs.html' %} 
    {% block head %}{% endblock %}
    <title>
        {% if debug %}DEBUG {% endif %}{% block title %}{% endblock %}
    </title>
</head>
<body>
    <nav class="purple">
        <div class="nav-wrapper">
            <a class="brand-logo" href="{% url 'pewad:index' %}">
                <img src="{% static 'pewad/images/mm-round.png' %}" height="30" width="30" alt="logo" style="position:relative; top:5px; margin-left:10px;"> PEWAD
            </a>
            <ul id="nav" class="right">
                <li><a class="nav-item nav-link" href="{% url 'pewad:contractlist' %}">Contracts</a></li>
                <li><a class="nav-item nav-link" href="{% url 'pewad:projectlist' %}">Projects</a></li>
                <li><a class="nav-item nav-link" href="{% url 'pewad:employeelist' %}">Employees</a></li>
            </ul>
        </div>
    </nav>
    <div id="modal-container"></div>
    <div id="content" class="container" style="width: 90%">
        <div class="row" id="alert_box">
            {% if messages %}
                <div id="alert_msgs" class="col s12 m12">
                    {% for message in messages %}
                    <div class="card {{ message.tags }}">
                        <div class="row">
                            <div class="col s12 m10">
                                <div class="card-content">
                                    <strong>{{ message }}</strong>
                                </div>
                            </div>
                            <div class="col s12 m2">
                                <i class="material-icons icon_style" id="alert_close" aria-hidden="true">close</i>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        {% block body %} {% endblock %} 
        {% block footer %} {% endblock %}
    </div>
    <script type="text/javascript">
        $('#alert_close').on('click', function () {
            /* Closes alert messages */
            $("#alert_box").fadeOut("slow", function () {});
        });

        function loadAndOpenModal(url) {
            /* Make a GET request for a form and launches it in a modal */
            $.get(url, function (result) {
                $('#modal-container').html(result);
                $('.modal').modal();
                $('#modal').modal('open');
            });
        }
    </script>
</body>
</html>

pewad/templates/pewad/contract_create_form.html
<div class="modal bottom-sheet" id="modal">
    <div class="modal-content">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat btn-small right">
            <i class="material-icons">close</i>
        </a>
        <h5>Create New Contract</h5>
        <div class="divider"></div>
        <div class="divider"></div>
        <form method="POST" action="{% url 'pewad:contractcreate' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create" class="waves-effect waves-green btn-flat btn small" />
        </form>
    </div>
</div>

pewad/templates/pewad/contract_list.html
{% extends 'pewad/list.html' %}

{% block extra-buttons %}
<a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Contract">
    <i class="material-icons left">note_add</i>Create New Contract</a>
{% endblock extra-buttons %}
{% block table-script %}
<script type="text/javascript">
    $(document).ready(function () {
        /* Build the table here; settings adjustments */
        $("#list-table").tabulator({
            ajaxURL: "{% url 'pewad:contractlistdata' %}", // Load table data
            clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
            layout: "fitDataFill", //fit columns to width of table (optional)
            initialSort: [{column: "fields.name", dir: "asc"},],
            columns: [ //Define Table Columns
                { title: "ID", field: "pk", sorter: "number" },
                { title: "Name", field: "fields.name", sorter: "string" },
                { title: "Number", field: "fields.number", sorter: "number" },
            ],
            rowClick: function (e, id) {
                location.href = id.row.data.pk;
            },
        });
    });

    $("#createbutton").click(function () {
        var url = "{% url 'pewad:contractcreate' %}"
        loadAndOpenModal(url);
    });
</script>
{% endblock table-script %}

pewad/templates/pewad/employee_list.html
{% extends 'pewad/list.html' %}

{% block extra-buttons %}
    <a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Employee">
        <i class="material-icons left">person_add</i>Create New Employee</a>
    <a id="emailallbutton" class="waves-effect waves-light btn-small" title="Email All Employees">
        <i class="material-icons left">email</i>Email All Employees</a>
    <a id="emailleadsbutton" class="waves-effect waves-light btn-small" title="Email All Leads">
        <i class="material-icons left">email</i>Email Lead Reports</a>
{% endblock extra-buttons %}
{% block table-script %}
    <script type="text/javascript">
        $(document).ready(function () {
            /* Build the table here; settings adjustments */
            $("#list-table").tabulator({
                ajaxURL: "{% url 'pewad:employeelistdata' %}", // Load table data
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                layout: "fitDataFill", //fit columns to width of table (optional)
                initialSort: [{ column: "fields.lname", dir: "asc" },],
                columns: [ //Define Table Columns
                    { title: "ID", field: "pk", sorter: "number" },
                    { title: "Last", field: "fields.lname", sorter: "string" },
                    { title: "First", field: "fields.fname", sorter: "string" },
                    { title: "Email", field: "fields.email", sorter: "string" }
                ],
                rowClick: function (e, id) {
                    location.href = id.row.data.pk;
                },
            });
        });

        $("#createbutton").click(function () {
            var url = "{% url 'pewad:employeecreate' %}"
            loadAndOpenModal(url);
        });
        $("#emailallbutton").click(function () {
            var url = "{% url 'pewad:employeeemailall' %}"
            $.get(url, function (result) { });
            M.toast({ html: 'Emailing all employees.' });
        });
        $("#emailleadsbutton").click(function() {
            var url = "{% url 'pewad:leademailall' %}";
            M.toast({ html: 'Emailing all Leads...' });
            $.get(url, function (result) { });
        });
    </script>
{% endblock table-script %}

pewad/templates/pewad/index.html
{% extends 'pewad/basehtml.html' %}
{% load static %}

{% block title %}Project: {{ passedValue }}{% endblock title %}

{% block body %}
    <h2>Employee Task Breakdown</h2>
    <div class="divider"></div>
    <div id="example-table"></div>

    <script type="text/javascript">
        var tableElem = $("#example-table");

        $(document).ready(function () {
            /* Build the main table here; settings adjustments */
            tableElem.tabulator({
                ajaxURL: "{% url 'pewad:loadtable' %}", // Load table data
                persistentLayout: false, // Enable column layout persistence
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                height: getViewableHeight(), // Set height of table to enable virtual DOM
                layout: "fitDataFill", // Fit columns to width of table (optional)
                layoutColumnsOnNewData:true, // fixes row heights (see: textarea) on data load
                resizableRows: true,
                columns: [ // Define Table Columns
                    { // Contract Column Group
                        title: "Contract",
                        columns: [
                            { title: "Number", field: "conNum", sorter: "string" },
                            { title: "Name", field: "conName", sorter: "string" },
                        ],
                    },
                    { title: "Project", field: "proj", sorter: "string" },
                    { // Lead Column Group
                        title: "Lead",
                        columns: [
                            { title: "Last", field: "leadLast", sorter: "string" },
                            { title: "First", field: "leadFirst", sorter: "string" },
                        ],
                    },
                    { // Employee Column Group
                        title: "Employee/Consultant",
                        columns: [
                            { title: "Last", field: "empLast", sorter: "string" },
                            { title: "First", field: "empFirst", sorter: "string" },
                        ],
                    },
                    { title: "WBS Hours", field: "hours", sorter: "number" },
                    { title: "Work Assignment", field: "assig", sorter: "string", sortable: false, formatter:"textarea"},
                ],
                rowClick: function (e, t) { //open record edit modal when the row is clicked
                    var url = "{% url 'pewad:workrecordupdate' 0 %}";
                    url = url.replace("0", t.row.data.pk);
                    loadAndOpenModal(url);
                },
            });
        });

        function getViewableHeight() {
            /* Get the available screen height; minus the content above the table and 15 for bottom padding. */
            return window.innerHeight - (tableElem.position().top) - 15;
        }
        
        $(window).resize(function () {
            /* Upon window resize, redraw the table after setting the new window height */
            tableElem.tabulator("setHeight", getViewableHeight());
            tableElem.tabulator("redraw");
        });

    </script>
{% endblock body %}

pewad/templates/pewad/project_create_form.html
<div class="modal bottom-sheet" id="modal">
    <div class="modal-content">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat btn-small right">
            <i class="material-icons">close</i>
        </a>
        <h5>Create New Project</h5>
        <div class="divider"></div>
        <div class="divider"></div>
        <form method="POST" action="{% url 'pewad:projectcreate' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create" class="waves-effect waves-green btn-flat btn-small" />
        </form>
    </div>
</div>

pewad/templates/pewad/project_list.html
{% extends 'pewad/list.html' %}

{% block extra-buttons %}
    <a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Project">
        <i class="material-icons left">playlist_add</i>Create New Project</a>
{% endblock extra-buttons %}
{% block table-script %}
    <script type="text/javascript">
        $(document).ready(function () {
            /* Build the table here; settings adjustments */
            $("#list-table").tabulator({
                ajaxURL: "{% url 'pewad:projectlistdata' %}", // Load table data
                clipboard: true, // Enable copy table to clipboard; helpful for paste to Excel
                layout: "fitDataFill", //fit columns to width of table (optional)
                initialSort: [{ column: "fields.abbr", dir: "asc" },],
                columns: [ //Define Table Columns
                    { title: "ID", field: "pk", sorter: "number" },
                    { title: "Abbreviation", field: "fields.abbr", sorter: "string" },
                    { title: "Name", field: "fields.name", sorter: "string" },
                ],
                rowClick: function (e, id) {
                    location.href = id.row.data.pk;
                },
            });
        });

        $("#createbutton").click(function () {
            var url = "{% url 'pewad:projectcreate' %}"
            loadAndOpenModal(url);
        });
    </script>
{% endblock table-script %}

pewad/templates/pewad/update.html
{% extends 'pewad/basehtml.html' %}
{% load materializecss %}

{% block body %}
    <div class="row">
        <div class="col s12">
            <h3>
                <span style="font-size: 0.75em">{{ object.classname | title }} Details: </span>
                <strong>{% block item-desc %}{% endblock item-desc %}</strong>
                <a href="#edit_card"><i class="material-icons">edit</i></a>
            </h3>
            <div class="divider"></div>
        </div>
    </div>
    <div class="row align-bottom">
        <div class="col s4">
            <h5>Associated Work Records</h5>
        </div>
        <div class="col s8">
            <div class="right">
                {% block helper-buttons %}{% endblock helper-buttons %}
                <a id="clipboardbutton" class="waves-effect waves-light btn-small" title="Copy to Clipboard">
                    <i class="material-icons left">filter_frames</i>Copy</a>
                <a id="createbutton" class="waves-effect waves-light btn-small" title="Create New Record">
                    <i class="material-icons left">note_add</i>New</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <div id="record-table"></div>
        </div>
    </div>
    <div class="row">
        <div class="col s8">
            <div class="card grey lighten-5" id="edit_card">
                <div class="card-content">
                    <h5>Edit {{ object.classname | title }}</h5>
                    <div class="divider"></div>
                    <div class="divider"></div>
                    <form method="post">
                        {% csrf_token %}
                        {{ form | materializecss }}
                        <button type="submit" class="waves-effect waves-yellow btn-flat green lighten-4">update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% block table-script %}{% endblock table-script %} 
    <script type="text/javascript">
        function workRecordRowClick(t) {
            // On row click, open a WorkRecord edit modal
            var url = "{% url 'pewad:workrecordupdate' 0 %}";
            url = url.replace("0", t.row.data.pk);
            loadAndOpenModal(url);
        }

        $("#createbutton").click(function () {
            loadAndOpenModal("{% url 'pewad:workrecordcreate' %}");
        });

        $("#clipboardbutton").click(function () {
            $("#record-table").tabulator("copyToClipboard"); //copy the table to the clipboard and include the column headers
            M.toast({ html: 'Table copied to clipboard!' });
        });
    </script>
{% endblock body %}